<a href="https://colab.research.google.com/github/ferozferoz/DeepLearn/blob/master/dino_name_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from keras.models import Sequential
from keras.preprocessing.text import Tokenizer
from keras.layers import Dense, Embedding
from keras.layers import LSTM

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [28]:
dino_file = open('/content/gdrive/My Drive/ColabNotebooks/dinos.txt','r',encoding='UTF-8')

import string
list_of_words = [word.lower() for word in dino_file]
character = string.printable
print(character)
char_index = dict(zip(range(1,len(character)),character))
max_character = 30
X = np.zeros((len(list_of_words),max_character,len(char_index)+1))

for i,word in enumerate(list_of_words):
  for j,character in enumerate(word):
    X[i][j][char_index.get(character)] = 1

print(X[0])
"""list_of_words = [word.lower() for word in dino_file]
tokenizer = Tokenizer(char_level=True )
tokenizer.fit_on_texts(list_of_words)
sequences = tokenizer.texts_to_sequences(list_of_words)"""










"""in order to generate new words we need to prepare RNN model that generates output sequence based on input sequence"""
"""unique_alphabets = set()
lines = []
for word in dino_file:
  lines.append(list(word.lower()))
  for alphabet in word:
    unique_alphabets.add(alphabet.lower())

X = []
y = []

char_to_index = {alpha:index for index,alpha in enumerate(sorted(unique_alphabets))}
index_to_char = {index:alpha for index,alpha in enumerate(sorted(unique_alphabets))}
word_length = max([len(line) for line in lines])
vocab_size = len(unique_alphabets)
char_to_index['\n'] = word_length
char_to_index[' '] = 0
index_to_char[0] = ' '
index_to_char[word_length] = '\n' """



0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ 	

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


"unique_alphabets = set()\nlines = []\nfor word in dino_file:\n  lines.append(list(word.lower()))\n  for alphabet in word:\n    unique_alphabets.add(alphabet.lower())\n\nX = []\ny = []\n\nchar_to_index = {alpha:index for index,alpha in enumerate(sorted(unique_alphabets))}\nindex_to_char = {index:alpha for index,alpha in enumerate(sorted(unique_alphabets))}\nword_length = max([len(line) for line in lines])\nvocab_size = len(unique_alphabets)\nchar_to_index['\n'] = word_length\nchar_to_index[' '] = 0\nindex_to_char[0] = ' '\nindex_to_char[word_length] = '\n' "

In [19]:
X = np.zeros((len(lines),word_length,vocab_size+1))
y = np.zeros((len(lines),word_length,vocab_size+1))

i=0
for word in lines:
  j=0
  k=0

  for alphas in word[:-1]:
    X[i][j][char_to_index[alphas]] = 1
    j = j+1
  for alphas in word[1:]:
    y[i][k][char_to_index[alphas]] = 1
    k = k+1
  i = i+1

print(X.shape)
print(y.shape)



(1536, 27, 28)
(1536, 27, 28)


In [22]:
model = Sequential()
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2, input_shape= (word_length,vocab_size+1) , return_sequences=True ,))
model.add(Dense(vocab_size+1, activation='softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.summary()



Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 27, 128)           80384     
_________________________________________________________________
dense_2 (Dense)              (None, 27, 28)            3612      
Total params: 83,996
Trainable params: 83,996
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.fit(X, y, epochs=15, validation_data=(X, y))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 1536 samples, validate on 1536 samples
Epoch 1/15





1536/1536 [==============================] - 5s 3ms/step - loss: 1.3035 - acc: 0.0700 - val_loss: 1.1756 - val_acc: 0.0898
Epoch 2/15
1536/1536 [==============================] - 2s 2ms/step - loss: 1.1482 - acc: 0.1016 - val_loss: 1.1157 - val_acc: 0.1056
Epoch 3/15
1536/1536 [==============================] - 3s 2ms/step - loss: 1.0882 - acc: 0.1300 - val_loss: 1.0371 - val_acc: 0.1542
Epoch 4/15
1536/1536 [==============================] - 3s 2ms/step - loss: 1.0023 - acc: 0.1624 - val_loss: 0.9457 - val_acc: 0.1761
Epoch 5/15
1536/1536 [==============================] - 3s 2ms/step - loss: 0.9351 - acc: 0.1785 - val_loss: 0.8975 - val_acc: 0.1884
Epoch 6/15
1536/1536 [==============================] - 3s 2ms/step - loss: 0.9045 - acc: 0.1833 - val_loss: 0.8730 - val_acc: 0.1913
Epoch 7/15
1536/1536 [========================

In [27]:
y_pred = model.predict_classes(X[:2])
print(y_pred)
y_pred_words = [[index_to_char[i] for i in word] for word in y_pred ]
print(y_pred_words)

[[14 14  8  1 18 15 19  1 21 18 21 19 27 21 19 27 19 27 27 27 27 27 27 27
  27 27 27]
 [14 14  1 15 19 15 19 27 21 27 21 27 27 27 27 27 27 27 27 27 27 27 27 27
  27 27 27]]
[['n', 'n', 'h', 'a', 'r', 'o', 's', 'a', 'u', 'r', 'u', 's', '\n', 'u', 's', '\n', 's', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n'], ['n', 'n', 'a', 'o', 's', 'o', 's', '\n', 'u', '\n', 'u', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n', '\n']]
